services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: always
    ports:
      - "80:80" #Http
      - "81:81" #Administración de la API
      - "443:443" #Https
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt    networks:
      - red-cba-sofia

  servidor-bd-sofia:
    image: mysql:8.0
    container_name: contenedor-servidor-bd
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - red-cba-sofia
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app_backend:
    build: .
    container_name: backend_sofia
    volumes:
      - .:/home/SOFIA
    environment:
      FLASK_ENV: development
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - red-cba-sofia
    depends_on:
      servidor-bd-sofia:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5050/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks: 
  red-cba-sofia: 
    name: red-cba-sofia-ejemplo

volumes:
  mysql-data:
    name: mysql-data